In [6]:
import duckdb

In [5]:
!pip install --quiet jupysql duckdb-engine

In [7]:
%load_ext sql
%config SqlMagic.autopandas = True
%config SqlMagic.feedback = False
%config SqlMagic.displaycon = False
%sql duckdb:///:default:

In [18]:
%%sql

create or replace table opensea_events as (
    select
        *
    from
        read_json_auto('../messages/*.jsonl')
);
select
    *
from
    opensea_messages;

,event,payload,ref,topic
0,phx_reply,"{'response': '{}', 'status': 'ok', 'event_type...",0.0,collection:*
1,phx_reply,"{'response': '{}', 'status': 'ok', 'event_type...",0.0,phoenix
2,item_transferred,"{'response': None, 'status': None, 'event_type...",NaN,collection:*
3,item_metadata_updated,"{'response': None, 'status': None, 'event_type...",NaN,collection:*
4,item_transferred,"{'response': None, 'status': None, 'event_type...",NaN,collection:*
...,...,...,...,...
751,item_metadata_updated,"{'response': None, 'status': None, 'event_type...",NaN,collection:*
752,item_metadata_updated,"{'response': None, 'status': None, 'event_type...",NaN,collection:*
753,item_metadata_updated,"{'response': None, 'status': None, 'event_type...",NaN,collection:*
754,item_transferred,"{'response': None, 'status': None, 'event_type...",NaN,collection:*
755,item_metadata_updated,"{'response': None, 'status': None, 'event_type...",NaN,collection:*

In [20]:
%%sql

create or replace view collection_events as (
    select
        *
    from
        opensea_events
    where
        topic = 'collection:*'
        and event != 'phx_reply'
);
select
    *
from
    collection_events;

,event,payload,ref,topic
0,item_transferred,"{'response': None, 'status': None, 'event_type...",NaN,collection:*
1,item_metadata_updated,"{'response': None, 'status': None, 'event_type...",NaN,collection:*
2,item_transferred,"{'response': None, 'status': None, 'event_type...",NaN,collection:*
3,item_transferred,"{'response': None, 'status': None, 'event_type...",NaN,collection:*
4,item_metadata_updated,"{'response': None, 'status': None, 'event_type...",NaN,collection:*
...,...,...,...,...
737,item_metadata_updated,"{'response': None, 'status': None, 'event_type...",NaN,collection:*
738,item_metadata_updated,"{'response': None, 'status': None, 'event_type...",NaN,collection:*
739,item_metadata_updated,"{'response': None, 'status': None, 'event_type...",NaN,collection:*
740,item_transferred,"{'response': None, 'status': None, 'event_type...",NaN,collection:*
741,item_metadata_updated,"{'response': None, 'status': None, 'event_type...",NaN,collection:*